version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  api:
    build: .
    container_name: node-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/db
    depends_on:
      - mongo
